baseurl = "https://rifewang.github.io"
title = "凌虚 Blog"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# disqusShortname = ""

[params]
  author = "凌虚"
  info = "Backend Developer and System Architect"
  description = "Lingxu's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/WechatIMG63.jpeg"
  #gravatar = ""

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"

  since = 2019

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/RifeWang/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://github.com/RifeWang/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://github.com/RifeWang/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "/posts/"
[[menu.main]]
  name = "Translation"
  weight = 1
  url  = "/translation/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "/about/"